version: '3'

services:

  cache-srv:
    image: registry.eshop.com/eshop/cache-srv:${TAG}
    container_name: cache-srv
    ports:
      - "7001:7001"
    environment:
      - spring.cloud.config.profile=product
      - spring.cloud.config.uri=http://192.168.100.80:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet

  member-api:
    image: registry.eshop.com/eshop/member-api:${TAG}
    container_name: member-api
    ports:
      - "1111:1111"
    environment:
      - spring.cloud.config.profile=product
      - spring.cloud.config.uri=http://192.168.100.80:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
          - /usr/local/eshop/media:/usr/local/eshop/media
    networks:
      - eshop_eshopNet
  merchant-api:
    image: registry.eshop.com/eshop/merchant-api:${TAG}
    container_name: merchant-api
    ports:
      - "2222:2222"
    environment:
      - spring.cloud.config.profile=product
      - spring.cloud.config.uri=http://192.168.100.80:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
          - /usr/local/eshop/media:/usr/local/eshop/media
    networks:
      - eshop_eshopNet
  operator-api:
    image: registry.eshop.com/eshop/operator-api:${TAG}
    container_name: operator-api
    ports:
      - "3333:3333"
    environment:
      - spring.cloud.config.profile=product
      - spring.cloud.config.uri=http://192.168.100.80:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  agent-api:
    image: registry.eshop.com/eshop/agent-api:${TAG}
    container_name: agent-api
    ports:
      - "4444:4444"
    environment:
      - spring.cloud.config.profile=product
      - spring.cloud.config.uri=http://192.168.100.80:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  external-api:
    image: registry.eshop.com/eshop/external-api:${TAG}
    container_name: external-api
    ports:
      - "5555:5555"
    environment:
      - spring.cloud.config.profile=product
      - spring.cloud.config.uri=http://192.168.100.80:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  jobs:
    image: registry.eshop.com/eshop/jobs:${TAG}
    container_name: jobs
    ports:
      - "6666:6666"
    environment:
      - spring.cloud.config.profile=product
      - spring.cloud.config.uri=http://192.168.100.80:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet

networks:
  eshop_eshopNet:
    external: true